version: "3"

services:
  tomcat:
    image: tomcat
    ports:
      - '8082:8080'
    volumes:
      - ./target/java01-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
      - ./logs:/usr/local/tomcat/logs
